"""
Django settings for SIH_DRF_Backend project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "drf_spectacular",
    "drf_spectacular_sidecar",  # Optional

    "rest_framework",
    "corsheaders",
    "django_extensions",

    "ML_Apps",
    "RAG_app",
    "WhatsApp_Gmail_APP",

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SIH_DRF_Backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SIH_DRF_Backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
        "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],    
        "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

        'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
        'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser',
                                'rest_framework.parsers.MultiPartParser',
                                'rest_framework.parsers.FormParser'],
}
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600

# Rag ---------------------------------------
# REST_FRAMEWORK = {
#     'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
#     'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser',
#                                'rest_framework.parsers.MultiPartParser',
#                                'rest_framework.parsers.FormParser'],
# }
SPECTACULAR_SETTINGS = {
        'TITLE': 'DRF backend API',
        'DESCRIPTION': 'PS : 102',
        'VERSION': '1.0.0',
        'SERVE_INCLUDE_SCHEMA': False,
        'SWAGGER_UI_SETTINGS': {
            'deepLinking': True,
            'displayOperationId': True,
        },
        'COMPONENT_SPLIT_REQUEST': True,
        
        # ... other settings like 'SECURITY' for authentication
    }


CORS_ALLOW_ALL_ORIGINS = True
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Uncomment if you have a static folder
]

# JWT_SECRET = os.environ.get("JWT_SECRET", "")
# JWT_ALG = os.environ.get("JWT_ALG", "HS256")
# JWT_AUD = os.environ.get("JWT_AUD") or None
# JWT_ISS = os.environ.get("JWT_ISS") or None

# ——— RAG settings (paths kept identical to your scripts)
DB_FAISS_PATH = str(BASE_DIR / 'vectorstore' / 'db_faiss')

import os, ast
def env_list(name, default=None):
    val = os.environ.get(name)
    if not val:
        return default or []
    val = val.strip()
    if val.startswith('[') and val.endswith(']'):
        try:
            parsed = ast.literal_eval(val)
            return [str(x).strip() for x in (parsed or []) if str(x).strip()]
        except Exception:
            pass
    return [s.strip() for s in val.split(',') if s.strip()]
    
RECEIVER_EMAILS = env_list("RECEIVER_EMAILS", [])
RECEIVERS_WHATSAPP_NUMBERS = env_list("RECEIVERS_WHATSAPP_NUMBERS", [])


MONGODB_URI = os.environ["MONGODB_URI"]
MONGODB_DB = os.environ.get("MONGODB_DB", "Dropout")

TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN")

TECH_MAIL_ID = os.environ.get("TECH_MAIL_ID")
TECH_MAIL_PASS = os.environ.get("TECH_MAIL_PASS")

SENDER_WHATSAPP_NUMBER = os.environ.get("SENDER_WHATSAPP_NUMBER")
# RECEIVERS_WHATSAPP_NUMBERS = os.environ.get("RECEIVERS_WHATSAPP_NUMBERS")
# RECEIVER_EMAILS = os.environ.get("RECEIVER_EMAILS")


# Optional default for non-E.164 input (used by WhatsApp normalizer)
DEFAULT_COUNTRY_CODE = '+91'



# ---- Email (Django email backend) ----
# Configure these for your SMTP (example uses Gmail)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = TECH_MAIL_ID             # sender email
EMAIL_HOST_PASSWORD = TECH_MAIL_PASS       # app-specific password
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER




